[platformio]
src_dir = src

[env:esp32]
platform = espressif32
board = esp32dev
framework = espidf
board_build.sdkconfig_defaults = sdkconfig.defaults
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu11
    -Wno-old-style-definition
    -Wno-missing-field-initializers
    -Iinclude
    -Iklipper_src/src
    -Iklipper_src/src/esp32
    -Iklipper_src/src/generic
monitor_speed = 250000
