#pragma once

#include "sdkconfig.h"

#define CONFIG_MACH_ESPRESSIF_ESP32 1
#define CONFIG_MACH_AVR 0
#define CONFIG_MACH_ATSAM 0
#define CONFIG_MACH_ATSAMD 0
#define CONFIG_MACH_LPC176X 0
#define CONFIG_MACH_STM32 0
#define CONFIG_MACH_HC32F460 0
#define CONFIG_MACH_RPXXXX 0
#define CONFIG_MACH_PRU 0
#define CONFIG_MACH_AR100 0
#define CONFIG_MACH_LINUX 0
#define CONFIG_MACH_SIMU 0
#define CONFIG_ESP32_SELECT 1
#define CONFIG_BOARD_DIRECTORY "esp32"
#define CONFIG_MACH_esp32 1
#define CONFIG_MCU "esp32"
#define CONFIG_CLOCK_FREQ 240000000

#define CONFIG_LOW_LEVEL_OPTIONS 0
#define CONFIG_HAVE_LIMITED_CODE_SIZE 0
#define CONFIG_SERIAL 1
#define CONFIG_SERIAL_BAUD 250000
#define CONFIG_UART_TX_PIN 1
#define CONFIG_UART_RX_PIN 3

#define CONFIG_HAVE_GPIO 1
#define CONFIG_HAVE_GPIO_ADC 1
#define CONFIG_HAVE_GPIO_SPI 1
#define CONFIG_HAVE_GPIO_I2C 0
#define CONFIG_HAVE_GPIO_HARD_PWM 1
#define CONFIG_HAVE_GPIO_SDIO 0
#define CONFIG_HAVE_CHIPID 0
#define CONFIG_HAVE_BOOTLOADER_REQUEST 0
#define CONFIG_HAVE_STRICT_TIMING 0
#define CONFIG_INLINE_STEPPER_HACK 0

#define CONFIG_WANT_ADC 1
#define CONFIG_WANT_SPI 1
#define CONFIG_WANT_SOFTWARE_SPI 1
#define CONFIG_WANT_I2C 0
#define CONFIG_WANT_SOFTWARE_I2C 0
#define CONFIG_WANT_HARD_PWM 1
#define CONFIG_WANT_BUTTONS 1
#define CONFIG_WANT_TMCUART 1
#define CONFIG_WANT_NEOPIXEL 1
#define CONFIG_WANT_PULSE_COUNTER 1
#define CONFIG_WANT_ST7920 1
#define CONFIG_WANT_HD44780 1
#define CONFIG_WANT_THERMOCOUPLE 1
#define CONFIG_WANT_ADXL345 1
#define CONFIG_WANT_LIS2DW 1
#define CONFIG_WANT_BMI160 1
#define CONFIG_WANT_MPU9250 0
#define CONFIG_WANT_ICM20948 0
#define CONFIG_WANT_HX71X 1
#define CONFIG_WANT_ADS1220 1
#define CONFIG_WANT_LDC1612 0
#define CONFIG_WANT_SENSOR_ANGLE 1
#define CONFIG_NEED_SENSOR_BULK 1
#define CONFIG_WANT_TRIGGER_ANALOG 1
#define CONFIG_NEED_SOS_FILTER 1

#define CONFIG_HAVE_GPIO_SR 0
#define CONFIG_SR_BYTE_NO 4
#define CONFIG_SR_PIN_DATA 27
#define CONFIG_SR_PIN_CLK 25
#define CONFIG_SR_PIN_LATCH 26
#define CONFIG_SR_CLOCK_FREQ_MHZ 10

#define CONFIG_ADC_REFERENCE_MV 3300
#define CONFIG_INITIAL_PINS ""
