
/* DO NOT EDIT! This is an autogenerated file. See scripts/buildcommands.py. */

#include "board/irq.h"
#include "board/pgm.h"
#include "command.h"
#include "compiler.h"
#include "initial_pins.h"

void
ctr_run_initfuncs(void)
{
    extern void alloc_init(void);
    alloc_init();
    extern void adc_init(void);
    adc_init();
    extern void serial_init(void);
    serial_init();
    extern void timer_init(void);
    timer_init();
    extern void initial_pins_setup(void);
    initial_pins_setup();
}

void
ctr_run_shutdownfuncs(void)
{
    extern void analog_in_shutdown(void);
    analog_in_shutdown();
    extern void move_reset(void);
    move_reset();
    extern void sendf_shutdown(void);
    sendf_shutdown();
    extern void digital_out_shutdown(void);
    digital_out_shutdown();
    extern void hd44780_shutdown(void);
    hd44780_shutdown();
    extern void st7920_shutdown(void);
    st7920_shutdown();
    extern void pwm_shutdown(void);
    pwm_shutdown();
    extern void spidev_shutdown(void);
    spidev_shutdown();
    extern void stepper_shutdown(void);
    stepper_shutdown();
    extern void tmcuart_shutdown(void);
    tmcuart_shutdown();
    extern void trsync_shutdown(void);
    trsync_shutdown();
}

void
ctr_run_taskfuncs(void)
{
    irq_poll();
    extern void analog_in_task(void);
    analog_in_task();
    irq_poll();
    extern void buttons_task(void);
    buttons_task();
    irq_poll();
    extern void watchdog_feed(void);
    watchdog_feed();
    irq_poll();
    extern void console_task(void);
    console_task();
    irq_poll();
    extern void timer_task(void);
    timer_task();
    irq_poll();
    extern void counter_task(void);
    counter_task();
    irq_poll();
    extern void ads1220_capture_task(void);
    ads1220_capture_task();
    irq_poll();
    extern void adxl345_task(void);
    adxl345_task();
    irq_poll();
    extern void spi_angle_task(void);
    spi_angle_task();
    irq_poll();
    extern void bmi160_task(void);
    bmi160_task();
    irq_poll();
    extern void hx71x_capture_task(void);
    hx71x_capture_task();
    irq_poll();
    extern void lis2dw_task(void);
    lis2dw_task();
    irq_poll();
    extern void thermocouple_task(void);
    thermocouple_task();
    irq_poll();
    extern void tmcuart_task(void);
    tmcuart_task();
    irq_poll();
    extern void trsync_task(void);
    trsync_task();
    irq_poll();
}

uint8_t __always_inline
ctr_lookup_static_string(const char *str)
{
    if (__builtin_strcmp(str, "Invalid analog_in bytes_per_report") == 0)
        return 2;
    if (__builtin_strcmp(str, "ADC out of range") == 0)
        return 3;
    if (__builtin_strcmp(str, "Command request") == 0)
        return 4;
    if (__builtin_strcmp(str, "config_reset only available when shutdown") == 0)
        return 5;
    if (__builtin_strcmp(str, "oids already allocated") == 0)
        return 6;
    if (__builtin_strcmp(str, "Can't assign oid") == 0)
        return 7;
    if (__builtin_strcmp(str, "Invalid oid type") == 0)
        return 8;
    if (__builtin_strcmp(str, "Already finalized") == 0)
        return 9;
    if (__builtin_strcmp(str, "Invalid move request size") == 0)
        return 10;
    if (__builtin_strcmp(str, "Move queue overflow") == 0)
        return 11;
    if (__builtin_strcmp(str, "alloc_chunks failed") == 0)
        return 12;
    if (__builtin_strcmp(str, "alloc_chunk failed") == 0)
        return 13;
    if (__builtin_strcmp(str, "Invalid buttons retransmit count") == 0)
        return 14;
    if (__builtin_strcmp(str, "Set button past maximum button count") == 0)
        return 15;
    if (__builtin_strcmp(str, "Max of 8 buttons") == 0)
        return 16;
    if (__builtin_strcmp(str, "Invalid command") == 0)
        return 17;
    if (__builtin_strcmp(str, "Message encode error") == 0)
        return 18;
    if (__builtin_strcmp(str, "Command parser error") == 0)
        return 19;
    if (__builtin_strcmp(str, "ADC: out of range or uncalibrated. Check and try increasing CONFIG_ADC_REFERENCE_MV (it might be slightly off)!") == 0)
        return 20;
    if (__builtin_strcmp(str, "ADC: conversion has not finished yet.") == 0)
        return 21;
    if (__builtin_strcmp(str, "ADC: no conversion has been started.") == 0)
        return 22;
    if (__builtin_strcmp(str, "ADC: can't run multiple conversions at once.") == 0)
        return 23;
    if (__builtin_strcmp(str, "ADC: could not configure pin as analog input") == 0)
        return 24;
    if (__builtin_strcmp(str, "ADC pin is not a valid ADC channel.") == 0)
        return 25;
    if (__builtin_strcmp(str, "ADC: could not get clock frequency.") == 0)
        return 26;
    if (__builtin_strcmp(str, "ADC calibrated mapping failed.") == 0)
        return 27;
    if (__builtin_strcmp(str, "ADC calibration failed.") == 0)
        return 28;
    if (__builtin_strcmp(str, "Input pin outside of range") == 0)
        return 29;
    if (__builtin_strcmp(str, "Output pin outside of range") == 0)
        return 30;
    if (__builtin_strcmp(str, "PWM pin outside of range") == 0)
        return 31;
    if (__builtin_strcmp(str, "Max amount of PWM channels assigned.") == 0)
        return 32;
    if (__builtin_strcmp(str, "Max amount of PWM timers assigned. See if you can use the same frequency.") == 0)
        return 33;
    if (__builtin_strcmp(str, "Main stopped.") == 0)
        return 34;
    if (__builtin_strcmp(str, "WDT: can't calculate watchdog prescaler.") == 0)
        return 35;
    if (__builtin_strcmp(str, "Rescheduled timer in the past") == 0)
        return 36;
    if (__builtin_strcmp(str, "update_digital_out not valid with active queue") == 0)
        return 37;
    if (__builtin_strcmp(str, "Scheduled digital out event will exceed max_duration") == 0)
        return 38;
    if (__builtin_strcmp(str, "Can not set soft pwm cycle ticks while updates pending") == 0)
        return 39;
    if (__builtin_strcmp(str, "Missed scheduling of next digital out event") == 0)
        return 40;
    if (__builtin_strcmp(str, "Invalid neopixel update command") == 0)
        return 41;
    if (__builtin_strcmp(str, "Invalid neopixel data_size") == 0)
        return 42;
    if (__builtin_strcmp(str, "Scheduled pwm event will exceed max_duration") == 0)
        return 43;
    if (__builtin_strcmp(str, "Missed scheduling of next hard pwm event") == 0)
        return 44;
    if (__builtin_strcmp(str, "Shutdown cleared when not shutdown") == 0)
        return 45;
    if (__builtin_strcmp(str, "Timer too close") == 0)
        return 46;
    if (__builtin_strcmp(str, "sentinel timer called") == 0)
        return 47;
    if (__builtin_strcmp(str, "angle sensor requires cs pin") == 0)
        return 48;
    if (__builtin_strcmp(str, "Invalid spi_angle chip type") == 0)
        return 49;
    if (__builtin_strcmp(str, "bus_type invalid") == 0)
        return 50;
    if (__builtin_strcmp(str, "bus_type i2c unsupported") == 0)
        return 51;
    if (__builtin_strcmp(str, "bus_type spi unsupported") == 0)
        return 52;
    if (__builtin_strcmp(str, "HX71x gain/channel out of range 1-4") == 0)
        return 53;
    if (__builtin_strcmp(str, "model type invalid") == 0)
        return 54;
    if (__builtin_strcmp(str, "Filter section index larger than max_sections") == 0)
        return 55;
    if (__builtin_strcmp(str, "Invalid spi config") == 0)
        return 56;
    if (__builtin_strcmp(str, "Can't reset time when stepper active") == 0)
        return 57;
    if (__builtin_strcmp(str, "Invalid count parameter") == 0)
        return 58;
    if (__builtin_strcmp(str, "Stepper too far in past") == 0)
        return 59;
    if (__builtin_strcmp(str, "Thermocouple reader fault") == 0)
        return 60;
    if (__builtin_strcmp(str, "Invalid thermocouple chip type") == 0)
        return 61;
    if (__builtin_strcmp(str, "tmcuart data too large") == 0)
        return 62;
    if (__builtin_strcmp(str, "Can't add signal that is already active") == 0)
        return 63;
    return 0xff;
}

const struct initial_pin_s initial_pins[] PROGMEM = {
};
const int initial_pins_size PROGMEM = ARRAY_SIZE(initial_pins);

static const uint8_t command_parameters0[] PROGMEM = {
    PT_byte, PT_uint32, PT_buffer };
static const uint8_t command_parameters1[] PROGMEM = {
    PT_uint32, PT_progmem_buffer };
static const uint8_t command_parameters2[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters3[] PROGMEM = {
    PT_uint32, PT_uint32 };
static const uint8_t command_parameters4[] PROGMEM = {
    PT_uint32 };
static const uint8_t command_parameters5[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_uint16 };
static const uint8_t command_parameters6[] PROGMEM = {
    PT_byte, PT_byte, PT_buffer };
static const uint8_t command_parameters7[] PROGMEM = {
    PT_buffer };
static const uint8_t command_parameters8[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters9[] PROGMEM = {
    PT_byte, PT_byte };
static const uint8_t command_parameters10[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters11[] PROGMEM = {
    PT_uint16 };
static const uint8_t command_parameters12[] PROGMEM = {
    PT_uint32, PT_uint16 };
static const uint8_t command_parameters13[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_uint32, PT_uint16 };
static const uint8_t command_parameters14[] PROGMEM = {
    PT_byte, PT_uint16, PT_buffer };
static const uint8_t command_parameters15[] PROGMEM = {
    PT_byte, PT_buffer };
static const uint8_t command_parameters16[] PROGMEM = {
    PT_byte, PT_int32 };
static const uint8_t command_parameters17[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte };
static const uint8_t command_parameters18[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters19[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters20[] PROGMEM = {
    PT_uint32, PT_byte };
static const uint8_t command_parameters21[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_byte, PT_uint16, PT_uint16, PT_byte };
static const uint8_t command_parameters22[] PROGMEM = {
    PT_byte, PT_uint32 };
static const uint8_t command_parameters23[] PROGMEM = {
    PT_byte };
static const uint8_t command_parameters24[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_byte };
static const uint8_t command_parameters25[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters26[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_byte, PT_uint32, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters27[] PROGMEM = {
    PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters28[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters29[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters30[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters31[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_uint32, PT_uint32 };
static const uint8_t command_parameters32[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte };
static const uint8_t command_parameters33[] PROGMEM = {
    PT_uint32, PT_uint32, PT_uint16 };
static const uint8_t command_parameters34[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16 };
static const uint8_t command_parameters35[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint16, PT_uint16, PT_uint32 };
static const uint8_t command_parameters36[] PROGMEM = {
    PT_byte, PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters37[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte };
static const uint8_t command_parameters38[] PROGMEM = {
    PT_byte, PT_int32, PT_int32, PT_byte, PT_byte };
static const uint8_t command_parameters39[] PROGMEM = {
    PT_byte, PT_byte, PT_int32, PT_int32 };
static const uint8_t command_parameters40[] PROGMEM = {
    PT_byte, PT_byte, PT_int32, PT_int32, PT_int32, PT_int32, PT_int32 };
static const uint8_t command_parameters41[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint16, PT_int16 };
static const uint8_t command_parameters42[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte, PT_uint32 };
static const uint8_t command_parameters43[] PROGMEM = {
    PT_byte, PT_uint32, PT_uint32, PT_uint32, PT_uint32, PT_byte };
static const uint8_t command_parameters44[] PROGMEM = {
    PT_byte, PT_buffer, PT_byte };
static const uint8_t command_parameters45[] PROGMEM = {
    PT_byte, PT_uint32, PT_byte, PT_uint32, PT_uint32 };
static const uint8_t command_parameters46[] PROGMEM = {
    PT_byte, PT_byte, PT_byte, PT_byte, PT_uint32, PT_uint32, PT_uint32 };
static const uint8_t command_parameters47[] PROGMEM = {
    PT_byte, PT_byte, PT_int32 };
static const uint8_t command_parameters48[] PROGMEM = {
    PT_byte, PT_int32, PT_int32 };

const struct command_encoder command_encoder_94 PROGMEM = {    
    // analog_in_state oid=%c next_clock=%u values=%*s
    .encoded_msgid=94, // msgid=94
    .num_params=3,
    .param_types = command_parameters0,
    .max_size=64,
};
const struct command_encoder command_encoder_0 PROGMEM = {    
    // identify_response offset=%u data=%.*s
    .encoded_msgid=0, // msgid=0
    .num_params=2,
    .param_types = command_parameters1,
    .max_size=64,
};
const struct command_encoder command_encoder_95 PROGMEM = {    
    // stats count=%u sum=%u sumsq=%u
    .encoded_msgid=95, // msgid=95
    .num_params=3,
    .param_types = command_parameters2,
    .max_size=21,
};
const struct command_encoder command_encoder_96 PROGMEM = {    
    // uptime high=%u clock=%u
    .encoded_msgid=96, // msgid=-32
    .num_params=2,
    .param_types = command_parameters3,
    .max_size=16,
};
const struct command_encoder command_encoder_97 PROGMEM = {    
    // clock clock=%u
    .encoded_msgid=97, // msgid=-31
    .num_params=1,
    .param_types = command_parameters4,
    .max_size=11,
};
const struct command_encoder command_encoder_98 PROGMEM = {    
    // config is_config=%c crc=%u is_shutdown=%c move_count=%hu
    .encoded_msgid=98, // msgid=-30
    .num_params=4,
    .param_types = command_parameters5,
    .max_size=18,
};
const struct command_encoder command_encoder_99 PROGMEM = {    
    // buttons_state oid=%c ack_count=%c state=%*s
    .encoded_msgid=99, // msgid=-29
    .num_params=3,
    .param_types = command_parameters6,
    .max_size=64,
};
const struct command_encoder command_encoder_100 PROGMEM = {    
    // pong data=%*s
    .encoded_msgid=100, // msgid=-28
    .num_params=1,
    .param_types = command_parameters7,
    .max_size=64,
};
const struct command_encoder command_encoder_101 PROGMEM = {    
    // debug_result val=%u
    .encoded_msgid=101, // msgid=-27
    .num_params=1,
    .param_types = command_parameters4,
    .max_size=11,
};
const struct command_encoder command_encoder_102 PROGMEM = {    
    // endstop_state oid=%c homing=%c next_clock=%u pin_value=%c
    .encoded_msgid=102, // msgid=-26
    .num_params=4,
    .param_types = command_parameters8,
    .max_size=17,
};
const struct command_encoder command_encoder_103 PROGMEM = {    
    // neopixel_result oid=%c success=%c
    .encoded_msgid=103, // msgid=-25
    .num_params=2,
    .param_types = command_parameters9,
    .max_size=10,
};
const struct command_encoder command_encoder_104 PROGMEM = {    
    // counter_state oid=%c next_clock=%u count=%u count_clock=%u
    .encoded_msgid=104, // msgid=-24
    .num_params=4,
    .param_types = command_parameters10,
    .max_size=23,
};
const struct command_encoder command_encoder_105 PROGMEM = {    
    // starting
    .encoded_msgid=105, // msgid=-23
    .num_params=0,
    .param_types = 0,
    .max_size=6,
};
const struct command_encoder command_encoder_106 PROGMEM = {    
    // is_shutdown static_string_id=%hu
    .encoded_msgid=106, // msgid=-22
    .num_params=1,
    .param_types = command_parameters11,
    .max_size=9,
};
const struct command_encoder command_encoder_107 PROGMEM = {    
    // shutdown clock=%u static_string_id=%hu
    .encoded_msgid=107, // msgid=-21
    .num_params=2,
    .param_types = command_parameters12,
    .max_size=14,
};
const struct command_encoder command_encoder_108 PROGMEM = {    
    // spi_angle_transfer_response oid=%c clock=%u response=%*s
    .encoded_msgid=108, // msgid=-20
    .num_params=3,
    .param_types = command_parameters0,
    .max_size=64,
};
const struct command_encoder command_encoder_109 PROGMEM = {    
    // sensor_bulk_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%u possible_overflows=%hu
    .encoded_msgid=109, // msgid=-19
    .num_params=6,
    .param_types = command_parameters13,
    .max_size=29,
};
const struct command_encoder command_encoder_110 PROGMEM = {    
    // sensor_bulk_data oid=%c sequence=%hu data=%*s
    .encoded_msgid=110, // msgid=-18
    .num_params=3,
    .param_types = command_parameters14,
    .max_size=64,
};
const struct command_encoder command_encoder_111 PROGMEM = {    
    // spi_transfer_response oid=%c response=%*s
    .encoded_msgid=111, // msgid=-17
    .num_params=2,
    .param_types = command_parameters15,
    .max_size=64,
};
const struct command_encoder command_encoder_112 PROGMEM = {    
    // stepper_position oid=%c pos=%i
    .encoded_msgid=112, // msgid=-16
    .num_params=2,
    .param_types = command_parameters16,
    .max_size=13,
};
const struct command_encoder command_encoder_113 PROGMEM = {    
    // thermocouple_result oid=%c next_clock=%u value=%u fault=%c
    .encoded_msgid=113, // msgid=-15
    .num_params=4,
    .param_types = command_parameters17,
    .max_size=20,
};
const struct command_encoder command_encoder_114 PROGMEM = {    
    // tmcuart_response oid=%c read=%*s
    .encoded_msgid=114, // msgid=-14
    .num_params=2,
    .param_types = command_parameters15,
    .max_size=64,
};
const struct command_encoder command_encoder_115 PROGMEM = {    
    // trigger_analog_state oid=%c homing=%c homing_clock=%u
    .encoded_msgid=115, // msgid=-13
    .num_params=3,
    .param_types = command_parameters18,
    .max_size=15,
};
const struct command_encoder command_encoder_116 PROGMEM = {    
    // trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u
    .encoded_msgid=116, // msgid=-12
    .num_params=4,
    .param_types = command_parameters19,
    .max_size=17,
};

const __always_inline struct command_encoder *
ctr_lookup_encoder(const char *str)
{
    if (__builtin_strcmp(str, "analog_in_state oid=%c next_clock=%u values=%*s") == 0)
        return &command_encoder_94;
    if (__builtin_strcmp(str, "identify_response offset=%u data=%.*s") == 0)
        return &command_encoder_0;
    if (__builtin_strcmp(str, "stats count=%u sum=%u sumsq=%u") == 0)
        return &command_encoder_95;
    if (__builtin_strcmp(str, "uptime high=%u clock=%u") == 0)
        return &command_encoder_96;
    if (__builtin_strcmp(str, "clock clock=%u") == 0)
        return &command_encoder_97;
    if (__builtin_strcmp(str, "config is_config=%c crc=%u is_shutdown=%c move_count=%hu") == 0)
        return &command_encoder_98;
    if (__builtin_strcmp(str, "buttons_state oid=%c ack_count=%c state=%*s") == 0)
        return &command_encoder_99;
    if (__builtin_strcmp(str, "pong data=%*s") == 0)
        return &command_encoder_100;
    if (__builtin_strcmp(str, "debug_result val=%u") == 0)
        return &command_encoder_101;
    if (__builtin_strcmp(str, "endstop_state oid=%c homing=%c next_clock=%u pin_value=%c") == 0)
        return &command_encoder_102;
    if (__builtin_strcmp(str, "neopixel_result oid=%c success=%c") == 0)
        return &command_encoder_103;
    if (__builtin_strcmp(str, "counter_state oid=%c next_clock=%u count=%u count_clock=%u") == 0)
        return &command_encoder_104;
    if (__builtin_strcmp(str, "starting") == 0)
        return &command_encoder_105;
    if (__builtin_strcmp(str, "is_shutdown static_string_id=%hu") == 0)
        return &command_encoder_106;
    if (__builtin_strcmp(str, "shutdown clock=%u static_string_id=%hu") == 0)
        return &command_encoder_107;
    if (__builtin_strcmp(str, "spi_angle_transfer_response oid=%c clock=%u response=%*s") == 0)
        return &command_encoder_108;
    if (__builtin_strcmp(str, "sensor_bulk_status oid=%c clock=%u query_ticks=%u next_sequence=%hu buffered=%u possible_overflows=%hu") == 0)
        return &command_encoder_109;
    if (__builtin_strcmp(str, "sensor_bulk_data oid=%c sequence=%hu data=%*s") == 0)
        return &command_encoder_110;
    if (__builtin_strcmp(str, "spi_transfer_response oid=%c response=%*s") == 0)
        return &command_encoder_111;
    if (__builtin_strcmp(str, "stepper_position oid=%c pos=%i") == 0)
        return &command_encoder_112;
    if (__builtin_strcmp(str, "thermocouple_result oid=%c next_clock=%u value=%u fault=%c") == 0)
        return &command_encoder_113;
    if (__builtin_strcmp(str, "tmcuart_response oid=%c read=%*s") == 0)
        return &command_encoder_114;
    if (__builtin_strcmp(str, "trigger_analog_state oid=%c homing=%c homing_clock=%u") == 0)
        return &command_encoder_115;
    if (__builtin_strcmp(str, "trsync_state oid=%c can_trigger=%c trigger_reason=%c clock=%u") == 0)
        return &command_encoder_116;
    return NULL;
}

const __always_inline struct command_encoder *
ctr_lookup_output(const char *str)
{
    
    return NULL;
}

extern void ads1220_attach_trigger_analog(uint32_t*);
extern void command_allocate_oids(uint32_t*);
extern void command_analog_in_attach_trigger_analog(uint32_t*);
extern void command_buttons_ack(uint32_t*);
extern void command_buttons_add(uint32_t*);
extern void command_buttons_query(uint32_t*);
extern void command_clear_shutdown(uint32_t*);
extern void command_config_ads1220(uint32_t*);
extern void command_config_adxl345(uint32_t*);
extern void command_config_analog_in(uint32_t*);
extern void command_config_bmi160(uint32_t*);
extern void command_config_buttons(uint32_t*);
extern void command_config_counter(uint32_t*);
extern void command_config_digital_out(uint32_t*);
extern void command_config_endstop(uint32_t*);
extern void command_config_hd44780(uint32_t*);
extern void command_config_hx71x(uint32_t*);
extern void command_config_lis2dw(uint32_t*);
extern void command_config_neopixel(uint32_t*);
extern void command_config_pwm_out(uint32_t*);
extern void command_config_sos_filter(uint32_t*);
extern void command_config_spi(uint32_t*);
extern void command_config_spi_angle(uint32_t*);
extern void command_config_spi_shutdown(uint32_t*);
extern void command_config_spi_without_cs(uint32_t*);
extern void command_config_st7920(uint32_t*);
extern void command_config_stepper(uint32_t*);
extern void command_config_thermocouple(uint32_t*);
extern void command_config_tmcuart(uint32_t*);
extern void command_config_trigger_analog(uint32_t*);
extern void command_config_trsync(uint32_t*);
extern void command_debug_nop(uint32_t*);
extern void command_debug_ping(uint32_t*);
extern void command_debug_read(uint32_t*);
extern void command_debug_write(uint32_t*);
extern void command_emergency_stop(uint32_t*);
extern void command_endstop_home(uint32_t*);
extern void command_endstop_query_state(uint32_t*);
extern void command_finalize_config(uint32_t*);
extern void command_get_clock(uint32_t*);
extern void command_get_config(uint32_t*);
extern void command_get_uptime(uint32_t*);
extern void command_hd44780_send_cmds(uint32_t*);
extern void command_hd44780_send_data(uint32_t*);
extern void command_identify(uint32_t*);
extern void command_neopixel_send(uint32_t*);
extern void command_neopixel_update(uint32_t*);
extern void command_query_ads1220(uint32_t*);
extern void command_query_ads1220_status(uint32_t*);
extern void command_query_adxl345(uint32_t*);
extern void command_query_adxl345_status(uint32_t*);
extern void command_query_analog_in(uint32_t*);
extern void command_query_bmi160(uint32_t*);
extern void command_query_bmi160_status(uint32_t*);
extern void command_query_counter(uint32_t*);
extern void command_query_hx71x(uint32_t*);
extern void command_query_hx71x_status(uint32_t*);
extern void command_query_lis2dw(uint32_t*);
extern void command_query_lis2dw_status(uint32_t*);
extern void command_query_spi_angle(uint32_t*);
extern void command_query_thermocouple(uint32_t*);
extern void command_queue_digital_out(uint32_t*);
extern void command_queue_pwm_out(uint32_t*);
extern void command_queue_step(uint32_t*);
extern void command_reset(uint32_t*);
extern void command_reset_step_clock(uint32_t*);
extern void command_set_digital_out(uint32_t*);
extern void command_set_digital_out_pwm_cycle(uint32_t*);
extern void command_set_next_step_dir(uint32_t*);
extern void command_set_pwm_out(uint32_t*);
extern void command_sos_filter_activate(uint32_t*);
extern void command_sos_filter_set_section(uint32_t*);
extern void command_sos_filter_set_state(uint32_t*);
extern void command_spi_angle_transfer(uint32_t*);
extern void command_spi_send(uint32_t*);
extern void command_spi_set_bus(uint32_t*);
extern void command_spi_set_sw_bus(uint32_t*);
extern void command_spi_transfer(uint32_t*);
extern void command_st7920_send_cmds(uint32_t*);
extern void command_st7920_send_data(uint32_t*);
extern void command_stepper_get_position(uint32_t*);
extern void command_stepper_stop_on_trigger(uint32_t*);
extern void command_tmcuart_send(uint32_t*);
extern void command_trigger_analog_home(uint32_t*);
extern void command_trigger_analog_query_state(uint32_t*);
extern void command_trigger_analog_set_offset_scale(uint32_t*);
extern void command_trigger_analog_set_raw_range(uint32_t*);
extern void command_trigger_analog_set_trigger(uint32_t*);
extern void command_trsync_set_timeout(uint32_t*);
extern void command_trsync_start(uint32_t*);
extern void command_trsync_trigger(uint32_t*);
extern void command_update_digital_out(uint32_t*);
extern void hx71x_attach_trigger_analog(uint32_t*);

const struct command_parser command_index[] PROGMEM = {
{
}, {
    // identify offset=%u count=%c
    .encoded_msgid=1, // msgid=1
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0x01,
    .func=command_identify
}, {
    // analog_in_attach_trigger_analog oid=%c trigger_analog_oid=%c
    .encoded_msgid=2, // msgid=2
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_analog_in_attach_trigger_analog
}, {
    // query_analog_in oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u bytes_per_report=%c min_value=%hu max_value=%hu range_check_count=%c
    .encoded_msgid=3, // msgid=3
    .num_params=9,
    .param_types = command_parameters21,
    .num_args=9,
    .flags=0,
    .func=command_query_analog_in
}, {
    // config_analog_in oid=%c pin=%u
    .encoded_msgid=4, // msgid=4
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_config_analog_in
}, {
    // clear_shutdown
    .encoded_msgid=5, // msgid=5
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_clear_shutdown
}, {
    // emergency_stop
    .encoded_msgid=6, // msgid=6
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_emergency_stop
}, {
    // get_uptime
    .encoded_msgid=7, // msgid=7
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_uptime
}, {
    // get_clock
    .encoded_msgid=8, // msgid=8
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_clock
}, {
    // finalize_config crc=%u
    .encoded_msgid=9, // msgid=9
    .num_params=1,
    .param_types = command_parameters4,
    .num_args=1,
    .flags=0,
    .func=command_finalize_config
}, {
    // get_config
    .encoded_msgid=10, // msgid=10
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_get_config
}, {
    // allocate_oids count=%c
    .encoded_msgid=11, // msgid=11
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_allocate_oids
}, {
    // buttons_ack oid=%c count=%c
    .encoded_msgid=12, // msgid=12
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_buttons_ack
}, {
    // buttons_query oid=%c clock=%u rest_ticks=%u retransmit_count=%c invert=%c
    .encoded_msgid=13, // msgid=13
    .num_params=5,
    .param_types = command_parameters24,
    .num_args=5,
    .flags=0,
    .func=command_buttons_query
}, {
    // buttons_add oid=%c pos=%c pin=%u pull_up=%c
    .encoded_msgid=14, // msgid=14
    .num_params=4,
    .param_types = command_parameters8,
    .num_args=4,
    .flags=0,
    .func=command_buttons_add
}, {
    // config_buttons oid=%c button_count=%c
    .encoded_msgid=15, // msgid=15
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_config_buttons
}, {
    // debug_nop
    .encoded_msgid=16, // msgid=16
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_debug_nop
}, {
    // debug_ping data=%*s
    .encoded_msgid=17, // msgid=17
    .num_params=1,
    .param_types = command_parameters7,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_ping
}, {
    // debug_write order=%c addr=%u val=%u
    .encoded_msgid=18, // msgid=18
    .num_params=3,
    .param_types = command_parameters25,
    .num_args=3,
    .flags=0x01,
    .func=command_debug_write
}, {
    // debug_read order=%c addr=%u
    .encoded_msgid=19, // msgid=19
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0x01,
    .func=command_debug_read
}, {
    // endstop_query_state oid=%c
    .encoded_msgid=20, // msgid=20
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_endstop_query_state
}, {
    // endstop_home oid=%c clock=%u sample_ticks=%u sample_count=%c rest_ticks=%u pin_value=%c trsync_oid=%c trigger_reason=%c
    .encoded_msgid=21, // msgid=21
    .num_params=8,
    .param_types = command_parameters26,
    .num_args=8,
    .flags=0,
    .func=command_endstop_home
}, {
    // config_endstop oid=%c pin=%c pull_up=%c
    .encoded_msgid=22, // msgid=22
    .num_params=3,
    .param_types = command_parameters27,
    .num_args=3,
    .flags=0,
    .func=command_config_endstop
}, {
    // reset
    .encoded_msgid=23, // msgid=23
    .num_params=0,
    .param_types = 0,
    .num_args=0,
    .flags=0x01,
    .func=command_reset
}, {
    // set_digital_out pin=%u value=%c
    .encoded_msgid=24, // msgid=24
    .num_params=2,
    .param_types = command_parameters20,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out
}, {
    // update_digital_out oid=%c value=%c
    .encoded_msgid=25, // msgid=25
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_update_digital_out
}, {
    // queue_digital_out oid=%c clock=%u on_ticks=%u
    .encoded_msgid=26, // msgid=26
    .num_params=3,
    .param_types = command_parameters25,
    .num_args=3,
    .flags=0,
    .func=command_queue_digital_out
}, {
    // set_digital_out_pwm_cycle oid=%c cycle_ticks=%u
    .encoded_msgid=27, // msgid=27
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_set_digital_out_pwm_cycle
}, {
    // config_digital_out oid=%c pin=%u value=%c default_value=%c max_duration=%u
    .encoded_msgid=28, // msgid=28
    .num_params=5,
    .param_types = command_parameters28,
    .num_args=5,
    .flags=0,
    .func=command_config_digital_out
}, {
    // hd44780_send_data oid=%c data=%*s
    .encoded_msgid=29, // msgid=29
    .num_params=2,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_data
}, {
    // hd44780_send_cmds oid=%c cmds=%*s
    .encoded_msgid=30, // msgid=30
    .num_params=2,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0,
    .func=command_hd44780_send_cmds
}, {
    // config_hd44780 oid=%c rs_pin=%u e_pin=%u d4_pin=%u d5_pin=%u d6_pin=%u d7_pin=%u delay_ticks=%u
    .encoded_msgid=31, // msgid=31
    .num_params=8,
    .param_types = command_parameters29,
    .num_args=8,
    .flags=0,
    .func=command_config_hd44780
}, {
    // st7920_send_data oid=%c data=%*s
    .encoded_msgid=32, // msgid=32
    .num_params=2,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_data
}, {
    // st7920_send_cmds oid=%c cmds=%*s
    .encoded_msgid=33, // msgid=33
    .num_params=2,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0,
    .func=command_st7920_send_cmds
}, {
    // config_st7920 oid=%c cs_pin=%u sclk_pin=%u sid_pin=%u sync_delay_ticks=%u cmd_delay_ticks=%u
    .encoded_msgid=34, // msgid=34
    .num_params=6,
    .param_types = command_parameters30,
    .num_args=6,
    .flags=0,
    .func=command_config_st7920
}, {
    // neopixel_send oid=%c
    .encoded_msgid=35, // msgid=35
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_neopixel_send
}, {
    // neopixel_update oid=%c pos=%hu data=%*s
    .encoded_msgid=36, // msgid=36
    .num_params=3,
    .param_types = command_parameters14,
    .num_args=4,
    .flags=0,
    .func=command_neopixel_update
}, {
    // config_neopixel oid=%c pin=%u data_size=%hu bit_max_ticks=%u reset_min_ticks=%u
    .encoded_msgid=37, // msgid=37
    .num_params=5,
    .param_types = command_parameters31,
    .num_args=5,
    .flags=0,
    .func=command_config_neopixel
}, {
    // query_counter oid=%c clock=%u poll_ticks=%u sample_ticks=%u
    .encoded_msgid=38, // msgid=38
    .num_params=4,
    .param_types = command_parameters10,
    .num_args=4,
    .flags=0,
    .func=command_query_counter
}, {
    // config_counter oid=%c pin=%u pull_up=%c
    .encoded_msgid=39, // msgid=39
    .num_params=3,
    .param_types = command_parameters32,
    .num_args=3,
    .flags=0,
    .func=command_config_counter
}, {
    // set_pwm_out pin=%u cycle_ticks=%u value=%hu
    .encoded_msgid=40, // msgid=40
    .num_params=3,
    .param_types = command_parameters33,
    .num_args=3,
    .flags=0,
    .func=command_set_pwm_out
}, {
    // queue_pwm_out oid=%c clock=%u value=%hu
    .encoded_msgid=41, // msgid=41
    .num_params=3,
    .param_types = command_parameters34,
    .num_args=3,
    .flags=0,
    .func=command_queue_pwm_out
}, {
    // config_pwm_out oid=%c pin=%u cycle_ticks=%u value=%hu default_value=%hu max_duration=%u
    .encoded_msgid=42, // msgid=42
    .num_params=6,
    .param_types = command_parameters35,
    .num_args=6,
    .flags=0,
    .func=command_config_pwm_out
}, {
    // query_ads1220_status oid=%c
    .encoded_msgid=43, // msgid=43
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_ads1220_status
}, {
    // query_ads1220 oid=%c rest_ticks=%u
    .encoded_msgid=44, // msgid=44
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_query_ads1220
}, {
    // ads1220_attach_trigger_analog oid=%c trigger_analog_oid=%c
    .encoded_msgid=45, // msgid=45
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=ads1220_attach_trigger_analog
}, {
    // config_ads1220 oid=%c spi_oid=%c data_ready_pin=%u
    .encoded_msgid=46, // msgid=46
    .num_params=3,
    .param_types = command_parameters18,
    .num_args=3,
    .flags=0,
    .func=command_config_ads1220
}, {
    // query_adxl345_status oid=%c
    .encoded_msgid=47, // msgid=47
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_adxl345_status
}, {
    // query_adxl345 oid=%c rest_ticks=%u
    .encoded_msgid=48, // msgid=48
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_query_adxl345
}, {
    // config_adxl345 oid=%c spi_oid=%c
    .encoded_msgid=49, // msgid=49
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_config_adxl345
}, {
    // spi_angle_transfer oid=%c data=%*s
    .encoded_msgid=50, // msgid=50
    .num_params=2,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0,
    .func=command_spi_angle_transfer
}, {
    // query_spi_angle oid=%c clock=%u rest_ticks=%u time_shift=%c
    .encoded_msgid=51, // msgid=51
    .num_params=4,
    .param_types = command_parameters17,
    .num_args=4,
    .flags=0,
    .func=command_query_spi_angle
}, {
    // config_spi_angle oid=%c spi_oid=%c spi_angle_type=%c
    .encoded_msgid=52, // msgid=52
    .num_params=3,
    .param_types = command_parameters27,
    .num_args=3,
    .flags=0,
    .func=command_config_spi_angle
}, {
    // query_bmi160_status oid=%c
    .encoded_msgid=53, // msgid=53
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_bmi160_status
}, {
    // query_bmi160 oid=%c rest_ticks=%u
    .encoded_msgid=54, // msgid=54
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_query_bmi160
}, {
    // config_bmi160 oid=%c bus_oid=%c bus_oid_type=%c
    .encoded_msgid=55, // msgid=55
    .num_params=3,
    .param_types = command_parameters27,
    .num_args=3,
    .flags=0,
    .func=command_config_bmi160
}, {
    // query_hx71x_status oid=%c
    .encoded_msgid=56, // msgid=56
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_hx71x_status
}, {
    // query_hx71x oid=%c rest_ticks=%u
    .encoded_msgid=57, // msgid=57
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_query_hx71x
}, {
    // hx71x_attach_trigger_analog oid=%c trigger_analog_oid=%c
    .encoded_msgid=58, // msgid=58
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=hx71x_attach_trigger_analog
}, {
    // config_hx71x oid=%c gain_channel=%c dout_pin=%u sclk_pin=%u
    .encoded_msgid=59, // msgid=59
    .num_params=4,
    .param_types = command_parameters36,
    .num_args=4,
    .flags=0,
    .func=command_config_hx71x
}, {
    // query_lis2dw_status oid=%c
    .encoded_msgid=60, // msgid=60
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_query_lis2dw_status
}, {
    // query_lis2dw oid=%c rest_ticks=%u
    .encoded_msgid=61, // msgid=61
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_query_lis2dw
}, {
    // config_lis2dw oid=%c bus_oid=%c bus_oid_type=%c lis_chip_type=%c
    .encoded_msgid=62, // msgid=62
    .num_params=4,
    .param_types = command_parameters37,
    .num_args=4,
    .flags=0,
    .func=command_config_lis2dw
}, {
    // sos_filter_set_active oid=%c n_sections=%c coeff_frac_bits=%c
    .encoded_msgid=63, // msgid=63
    .num_params=3,
    .param_types = command_parameters27,
    .num_args=3,
    .flags=0,
    .func=command_sos_filter_activate
}, {
    // sos_filter_set_offset_scale oid=%c offset=%i scale=%i scale_frac_bits=%c auto_offset=%c
    .encoded_msgid=64, // msgid=64
    .num_params=5,
    .param_types = command_parameters38,
    .num_args=5,
    .flags=0,
    .func=command_trigger_analog_set_offset_scale
}, {
    // sos_filter_set_state oid=%c section_idx=%c state0=%i state1=%i
    .encoded_msgid=65, // msgid=65
    .num_params=4,
    .param_types = command_parameters39,
    .num_args=4,
    .flags=0,
    .func=command_sos_filter_set_state
}, {
    // sos_filter_set_section oid=%c section_idx=%c sos0=%i sos1=%i sos2=%i sos3=%i sos4=%i
    .encoded_msgid=66, // msgid=66
    .num_params=7,
    .param_types = command_parameters40,
    .num_args=7,
    .flags=0,
    .func=command_sos_filter_set_section
}, {
    // config_sos_filter oid=%c max_sections=%c
    .encoded_msgid=67, // msgid=67
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_config_sos_filter
}, {
    // spi_set_sw_bus oid=%c miso_pin=%u mosi_pin=%u sclk_pin=%u mode=%u pulse_ticks=%u
    .encoded_msgid=68, // msgid=68
    .num_params=6,
    .param_types = command_parameters30,
    .num_args=6,
    .flags=0,
    .func=command_spi_set_sw_bus
}, {
    // config_spi_shutdown oid=%c spi_oid=%c shutdown_msg=%*s
    .encoded_msgid=69, // msgid=69
    .num_params=3,
    .param_types = command_parameters6,
    .num_args=4,
    .flags=0,
    .func=command_config_spi_shutdown
}, {
    // spi_send oid=%c data=%*s
    .encoded_msgid=70, // msgid=70
    .num_params=2,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0,
    .func=command_spi_send
}, {
    // spi_transfer oid=%c data=%*s
    .encoded_msgid=71, // msgid=71
    .num_params=2,
    .param_types = command_parameters15,
    .num_args=3,
    .flags=0,
    .func=command_spi_transfer
}, {
    // spi_set_bus oid=%c spi_bus=%u mode=%u rate=%u
    .encoded_msgid=72, // msgid=72
    .num_params=4,
    .param_types = command_parameters10,
    .num_args=4,
    .flags=0,
    .func=command_spi_set_bus
}, {
    // config_spi_without_cs oid=%c
    .encoded_msgid=73, // msgid=73
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_spi_without_cs
}, {
    // config_spi oid=%c pin=%u cs_active_high=%c
    .encoded_msgid=74, // msgid=74
    .num_params=3,
    .param_types = command_parameters32,
    .num_args=3,
    .flags=0,
    .func=command_config_spi
}, {
    // stepper_stop_on_trigger oid=%c trsync_oid=%c
    .encoded_msgid=75, // msgid=75
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_stepper_stop_on_trigger
}, {
    // stepper_get_position oid=%c
    .encoded_msgid=76, // msgid=76
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_stepper_get_position
}, {
    // reset_step_clock oid=%c clock=%u
    .encoded_msgid=77, // msgid=77
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_reset_step_clock
}, {
    // set_next_step_dir oid=%c dir=%c
    .encoded_msgid=78, // msgid=78
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_set_next_step_dir
}, {
    // queue_step oid=%c interval=%u count=%hu add=%hi
    .encoded_msgid=79, // msgid=79
    .num_params=4,
    .param_types = command_parameters41,
    .num_args=4,
    .flags=0,
    .func=command_queue_step
}, {
    // config_stepper oid=%c step_pin=%c dir_pin=%c invert_step=%c step_pulse_ticks=%u
    .encoded_msgid=80, // msgid=80
    .num_params=5,
    .param_types = command_parameters42,
    .num_args=5,
    .flags=0,
    .func=command_config_stepper
}, {
    // query_thermocouple oid=%c clock=%u rest_ticks=%u min_value=%u max_value=%u max_invalid_count=%c
    .encoded_msgid=81, // msgid=81
    .num_params=6,
    .param_types = command_parameters43,
    .num_args=6,
    .flags=0,
    .func=command_query_thermocouple
}, {
    // config_thermocouple oid=%c spi_oid=%c thermocouple_type=%c
    .encoded_msgid=82, // msgid=82
    .num_params=3,
    .param_types = command_parameters27,
    .num_args=3,
    .flags=0,
    .func=command_config_thermocouple
}, {
    // tmcuart_send oid=%c write=%*s read=%c
    .encoded_msgid=83, // msgid=83
    .num_params=3,
    .param_types = command_parameters44,
    .num_args=4,
    .flags=0,
    .func=command_tmcuart_send
}, {
    // config_tmcuart oid=%c rx_pin=%u pull_up=%c tx_pin=%u bit_time=%u
    .encoded_msgid=84, // msgid=84
    .num_params=5,
    .param_types = command_parameters45,
    .num_args=5,
    .flags=0,
    .func=command_config_tmcuart
}, {
    // trigger_analog_query_state oid=%c
    .encoded_msgid=85, // msgid=85
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_trigger_analog_query_state
}, {
    // trigger_analog_home oid=%c trsync_oid=%c trigger_reason=%c error_reason=%c clock=%u monitor_ticks=%u monitor_max=%u
    .encoded_msgid=86, // msgid=86
    .num_params=7,
    .param_types = command_parameters46,
    .num_args=7,
    .flags=0,
    .func=command_trigger_analog_home
}, {
    // trigger_analog_set_trigger oid=%c trigger_analog_type=%c trigger_value=%i
    .encoded_msgid=87, // msgid=87
    .num_params=3,
    .param_types = command_parameters47,
    .num_args=3,
    .flags=0,
    .func=command_trigger_analog_set_trigger
}, {
    // trigger_analog_set_raw_range oid=%c raw_min=%i raw_max=%i
    .encoded_msgid=88, // msgid=88
    .num_params=3,
    .param_types = command_parameters48,
    .num_args=3,
    .flags=0,
    .func=command_trigger_analog_set_raw_range
}, {
    // config_trigger_analog oid=%c sos_filter_oid=%c
    .encoded_msgid=89, // msgid=89
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_config_trigger_analog
}, {
    // trsync_trigger oid=%c reason=%c
    .encoded_msgid=90, // msgid=90
    .num_params=2,
    .param_types = command_parameters9,
    .num_args=2,
    .flags=0,
    .func=command_trsync_trigger
}, {
    // trsync_set_timeout oid=%c clock=%u
    .encoded_msgid=91, // msgid=91
    .num_params=2,
    .param_types = command_parameters22,
    .num_args=2,
    .flags=0,
    .func=command_trsync_set_timeout
}, {
    // trsync_start oid=%c report_clock=%u report_ticks=%u expire_reason=%c
    .encoded_msgid=92, // msgid=92
    .num_params=4,
    .param_types = command_parameters17,
    .num_args=4,
    .flags=0,
    .func=command_trsync_start
}, {
    // config_trsync oid=%c
    .encoded_msgid=93, // msgid=93
    .num_params=1,
    .param_types = command_parameters23,
    .num_args=1,
    .flags=0,
    .func=command_config_trsync
},
};

const uint16_t command_index_size PROGMEM = ARRAY_SIZE(command_index);

// version: ?-20260513_132045-Mair.lan
// build_versions: gcc: (crosstool-NG esp-15.2.0_20251204) 15.2.0 binutils: (crosstool-NG esp-15.2.0_20251204) 2.45

const uint8_t command_identify_data[] PROGMEM = {
    0x78, 0xda, 0x9d, 0x59, 0x7b, 0x6f, 0xe3, 0x36,
    0x12, 0xff, 0x2a, 0x3c, 0x03, 0xc5, 0xb5, 0x87,
    0x24, 0x67, 0xc9, 0xcf, 0x04, 0x28, 0x0e, 0x69,
    0xe2, 0xdd, 0x06, 0xdd, 0x24, 0xdb, 0x24, 0xdb,
    0x2d, 0x70, 0x38, 0x10, 0x8a, 0x44, 0xdb, 0x44,
    0x64, 0x49, 0x15, 0xa5, 0x4d, 0x72, 0xc5, 0x7e,
    0xf7, 0x9b, 0x87, 0xf8, 0x90, 0xec, 0xb4, 0x87,
    0xfa, 0x1f, 0x4b, 0xe4, 0xcc, 0x90, 0x1c, 0xce,
    0xe3, 0x37, 0xa3, 0xdf, 0x47, 0x49, 0x55, 0x8d,
    0xce, 0x46, 0x3f, 0xe5, 0xba, 0xaa, 0x54, 0x3d,
    0x3a, 0x1a, 0x3d, 0xb6, 0x3a, 0xcf, 0xe4, 0x17,
    0x55, 0x1b, 0x5d, 0x16, 0x06, 0xa6, 0x36, 0x69,
    0x7a, 0x26, 0xbe, 0x4d, 0xeb, 0xd2, 0x98, 0xa6,
    0x2c, 0xf3, 0xe3, 0x9b, 0xf7, 0x42, 0x99, 0xea,
    0x38, 0x9a, 0x9d, 0xc4, 0x27, 0x63, 0x19, 0x8f,
    0xe3, 0x59, 0x14, 0x8f, 0xa7, 0xdf, 0x09, 0x1e,
    0x10, 0x8f, 0xba, 0x68, 0x1b, 0x9d, 0x9b, 0xff,
    0x8b, 0x27, 0x3e, 0x99, 0xce, 0x60, 0xcd, 0xb4,
    0xdc, 0xed, 0x92, 0x22, 0x83, 0xd5, 0x7e, 0x1f,
    0x25, 0x99, 0x89, 0xe2, 0x78, 0x2c, 0x93, 0xa6,
    0x49, 0xd2, 0xad, 0x6c, 0x6a, 0xbd, 0xd9, 0xa8,
    0x5a, 0x26, 0x45, 0x92, 0x97, 0x1b, 0x51, 0xea,
    0xec, 0xfb, 0x6f, 0x52, 0xd1, 0x1f, 0x95, 0x3c,
    0x3a, 0x3a, 0x9b, 0xce, 0x8e, 0x46, 0x49, 0x9e,
    0x97, 0x69, 0xd2, 0x28, 0x1c, 0x34, 0x22, 0x2d,
    0xdb, 0xa2, 0xa1, 0xb9, 0x28, 0x82, 0x39, 0x26,
    0xd7, 0xc5, 0x5f, 0x92, 0x1e, 0xa3, 0x72, 0x9a,
    0x06, 0xb4, 0x22, 0x93, 0xf4, 0xc9, 0x12, 0x07,
    0x2b, 0x84, 0x04, 0x59, 0x66, 0x09, 0xaa, 0xd2,
    0xd0, 0x9f, 0x2e, 0xbe, 0xff, 0xa6, 0x15, 0x55,
    0x9b, 0xe7, 0xb2, 0xad, 0x98, 0x61, 0xea, 0x19,
    0x7e, 0x6b, 0x55, 0xfd, 0xea, 0x64, 0xc2, 0x11,
    0x9e, 0x90, 0xba, 0x56, 0xa6, 0x91, 0x8d, 0x4e,
    0x9f, 0x0c, 0xbf, 0x35, 0x75, 0x52, 0x98, 0x9d,
    0x6e, 0xa4, 0x5d, 0x55, 0xe8, 0x02, 0xae, 0xaa,
    0x5b, 0x7f, 0x02, 0x9a, 0xcc, 0x55, 0x52, 0x4b,
    0xb3, 0x6d, 0x9b, 0xac, 0x7c, 0x2e, 0x46, 0x67,
    0x33, 0x54, 0x6e, 0xb1, 0xd6, 0x1b, 0xd9, 0xe9,
    0xd5, 0x2e, 0x61, 0x2a, 0xdd, 0x1d, 0x4c, 0x64,
    0x49, 0x93, 0xc8, 0x5a, 0x25, 0xd9, 0xab, 0xe4,
    0x4d, 0x82, 0x22, 0xe7, 0x01, 0xdf, 0x4b, 0x3e,
    0x99, 0xce, 0xf6, 0xf9, 0x80, 0xea, 0xd4, 0x53,
    0x59, 0xcd, 0xba, 0x53, 0x5b, 0x49, 0x8e, 0xe4,
    0x71, 0xa7, 0xa3, 0xb9, 0x5b, 0xff, 0xb1, 0x35,
    0xb2, 0xff, 0x28, 0x9b, 0xd7, 0x4a, 0x91, 0xdc,
    0x99, 0xdf, 0x75, 0xa7, 0x1e, 0xcf, 0x85, 0xaf,
    0x32, 0xd0, 0xb9, 0x27, 0xa5, 0x41, 0x55, 0xf7,
    0x37, 0xd0, 0xd3, 0xf7, 0xc4, 0xef, 0x37, 0xd3,
    0x1b, 0xdd, 0x24, 0xb9, 0x2c, 0xdb, 0x66, 0xc0,
    0xf0, 0x25, 0xc9, 0x5b, 0x45, 0x6a, 0x51, 0xeb,
    0xa4, 0xcd, 0x1b, 0xe9, 0x06, 0x76, 0xc9, 0x8b,
    0xcc, 0xda, 0x3a, 0x69, 0xc0, 0x31, 0xe8, 0x6c,
    0xf1, 0xd2, 0xc9, 0x53, 0x60, 0xbd, 0x4d, 0x59,
    0xf5, 0x64, 0xa5, 0xbd, 0xc5, 0xe3, 0xd8, 0x11,
    0x6f, 0xb3, 0xe9, 0x74, 0xb1, 0x74, 0xaa, 0xa8,
    0x4d, 0xa7, 0x77, 0xa1, 0xec, 0x43, 0x36, 0x75,
    0x4f, 0x33, 0xf7, 0x34, 0x77, 0x4f, 0x0b, 0xf7,
    0xa4, 0xf2, 0xe4, 0xd5, 0x19, 0x08, 0x9c, 0x30,
    0xf2, 0x8b, 0xbc, 0x2c, 0xa2, 0x17, 0xbb, 0xc4,
    0x26, 0x01, 0x9b, 0x4f, 0xb7, 0x49, 0x51, 0xa8,
    0x9c, 0xce, 0x06, 0xe7, 0xb6, 0x32, 0x4c, 0x9a,
    0x3f, 0xb9, 0x8b, 0x9f, 0x79, 0x15, 0xe5, 0xda,
    0xc4, 0xd9, 0xf3, 0x9f, 0xdf, 0x97, 0x00, 0x42,
    0x90, 0xad, 0x2b, 0x7f, 0x81, 0x73, 0x7f, 0xd6,
    0x42, 0x95, 0x95, 0x7e, 0x51, 0xf9, 0x40, 0xcb,
    0x64, 0x73, 0x46, 0xff, 0x17, 0xe8, 0xb7, 0x2d,
    0xc4, 0x8c, 0x46, 0xa2, 0x76, 0x03, 0x4b, 0x37,
    0x0a, 0x86, 0x60, 0xd3, 0xc1, 0xd9, 0x16, 0x4e,
    0x68, 0xf5, 0xbc, 0x3b, 0x70, 0x73, 0xe9, 0x2b,
    0x58, 0xbf, 0x97, 0xd1, 0xdd, 0xdb, 0xb6, 0x1d,
    0xde, 0x24, 0x8c, 0xec, 0x5d, 0xe5, 0xd4, 0xef,
    0xd8, 0x94, 0x46, 0xae, 0x75, 0x1e, 0x98, 0x12,
    0x52, 0x1b, 0x95, 0x22, 0xb1, 0xe1, 0xf3, 0xf9,
    0xad, 0x80, 0x3f, 0x0c, 0xb7, 0x81, 0xe1, 0xa1,
    0xd1, 0x5f, 0x94, 0xdc, 0xea, 0xcd, 0x96, 0xe8,
    0x17, 0xd3, 0x90, 0x1e, 0x9c, 0x65, 0x93, 0xab,
    0x03, 0x8e, 0xe8, 0xe6, 0x02, 0x57, 0x88, 0x7b,
    0x9c, 0xd6, 0xb1, 0x0f, 0x31, 0x77, 0x53, 0x72,
    0x67, 0x36, 0xdf, 0x7f, 0xf3, 0x0f, 0x88, 0xa5,
    0xf3, 0xd3, 0x1e, 0xef, 0xb3, 0x6e, 0xb6, 0x78,
    0xed, 0xa9, 0xf5, 0x26, 0xd8, 0xd7, 0xc4, 0x53,
    0x34, 0x8b, 0x53, 0x1f, 0x1d, 0x52, 0x73, 0xc0,
    0x3a, 0x84, 0x81, 0x4b, 0xb7, 0x8f, 0xaf, 0x45,
    0x2a, 0xfb, 0xd6, 0x27, 0xd2, 0x5d, 0x26, 0xf7,
    0x0c, 0x32, 0x38, 0x79, 0xa3, 0x30, 0xc5, 0xb8,
    0xad, 0xc3, 0xab, 0xec, 0xfc, 0x24, 0xd3, 0xb5,
    0x7d, 0xe4, 0x78, 0x46, 0xc4, 0x9e, 0xaa, 0xcd,
    0x8d, 0x0a, 0x84, 0x2e, 0xc7, 0x4e, 0x68, 0xb3,
    0x55, 0xf5, 0xae, 0x04, 0xd7, 0xaf, 0x0e, 0x6a,
    0x34, 0x9c, 0xf6, 0x4a, 0x5d, 0x7a, 0xa5, 0x36,
    0xbb, 0xb4, 0x4d, 0x6a, 0x67, 0x49, 0xf5, 0x8b,
    0xdc, 0x8b, 0x1b, 0xa2, 0x71, 0x83, 0x68, 0xa7,
    0x8d, 0xde, 0x29, 0xde, 0x85, 0x3f, 0xda, 0xe1,
    0x34, 0xe2, 0x0d, 0xc9, 0x45, 0xcc, 0xe5, 0x69,
    0xc0, 0x83, 0x3a, 0x74, 0x57, 0x71, 0x0a, 0x57,
    0x91, 0xa9, 0xc7, 0x16, 0x3c, 0xa6, 0x84, 0x84,
    0x1c, 0xcd, 0xed, 0x2b, 0x2c, 0xbd, 0x21, 0x77,
    0xe1, 0x4b, 0x8d, 0x16, 0x76, 0x02, 0x23, 0xb6,
    0x28, 0xeb, 0x4c, 0xd5, 0xb8, 0x18, 0x24, 0x9c,
    0x9a, 0xb6, 0x15, 0x9d, 0x5a, 0x82, 0xe7, 0x5a,
    0x37, 0x6a, 0x8f, 0x02, 0xfd, 0x82, 0x09, 0x21,
    0x7a, 0xa9, 0x9d, 0xaa, 0x37, 0xaa, 0x48, 0x5f,
    0x25, 0x46, 0x2f, 0x30, 0x19, 0x18, 0xe2, 0x48,
    0x26, 0xb7, 0xe5, 0x4e, 0xed, 0xe5, 0x23, 0x93,
    0xec, 0xaa, 0xd0, 0xc7, 0xba, 0x77, 0x97, 0x8d,
    0xfa, 0xf9, 0x0a, 0xb6, 0xee, 0xa3, 0x27, 0x9f,
    0x57, 0x0e, 0x52, 0x2c, 0x1c, 0xc2, 0xa0, 0x0b,
    0x62, 0x80, 0x8c, 0xfc, 0xe2, 0x94, 0x0d, 0x61,
    0x4f, 0x49, 0xa3, 0x9c, 0x86, 0x62, 0xb8, 0xf5,
    0xb5, 0x06, 0x0d, 0x43, 0xd4, 0x90, 0xac, 0x44,
    0x91, 0xd6, 0x29, 0x9d, 0x05, 0xce, 0xbc, 0x81,
    0x80, 0x41, 0xfb, 0x04, 0x2d, 0x77, 0x6f, 0x44,
    0x03, 0x07, 0x1d, 0xf3, 0x7b, 0x5b, 0xe1, 0xdd,
    0x81, 0xd5, 0x1f, 0x8d, 0xba, 0x08, 0x0c, 0x5e,
    0x5d, 0x64, 0x12, 0xec, 0xd6, 0x25, 0x18, 0x7c,
    0x66, 0x45, 0x4f, 0xc6, 0x03, 0x32, 0xbc, 0x03,
    0x11, 0xa4, 0x4c, 0x26, 0x8b, 0x61, 0x69, 0x0a,
    0xb5, 0x7f, 0x09, 0x52, 0xcc, 0x60, 0xab, 0x3a,
    0x53, 0x45, 0xa3, 0xd7, 0x90, 0xfc, 0xd7, 0x6b,
    0x88, 0x7a, 0xe4, 0x49, 0x3e, 0xbf, 0x1d, 0x8d,
    0x6c, 0x04, 0xa5, 0x5d, 0x38, 0x6d, 0x4c, 0x66,
    0xc1, 0x4c, 0x5b, 0x65, 0x5e, 0x53, 0x0c, 0x38,
    0xb6, 0x6d, 0xb0, 0xc9, 0x09, 0xdc, 0x2b, 0xab,
    0x74, 0x80, 0x02, 0x7a, 0xf7, 0x05, 0x51, 0x70,
    0x3a, 0xa0, 0xa3, 0x2b, 0x68, 0x7d, 0xc0, 0x98,
    0x4e, 0x3c, 0x41, 0x0f, 0x16, 0x0c, 0x05, 0x2d,
    0x07, 0x74, 0x7b, 0x82, 0x16, 0x8e, 0x60, 0x88,
    0x1c, 0xfe, 0xa2, 0xb1, 0x3d, 0xbe, 0x36, 0x0a,
    0xa2, 0x16, 0xd9, 0x54, 0x55, 0x12, 0x24, 0x12,
    0x3b, 0x6f, 0x80, 0x5d, 0xd0, 0xf7, 0x6f, 0x80,
    0xa4, 0x36, 0x20, 0x6c, 0xab, 0xd2, 0xa7, 0x00,
    0x4f, 0xb8, 0xf3, 0xf5, 0xd1, 0xca, 0xe0, 0x78,
    0xb3, 0x69, 0x9f, 0x6c, 0x78, 0xba, 0x99, 0x13,
    0x33, 0x00, 0x25, 0xee, 0x6c, 0x55, 0x09, 0xe1,
    0x65, 0x78, 0xb2, 0x20, 0x6c, 0x3a, 0xfd, 0xf5,
    0xd2, 0xf8, 0x70, 0x1b, 0x8b, 0x1e, 0xd5, 0xde,
    0x2e, 0xdc, 0xad, 0xf7, 0x53, 0xf9, 0x40, 0xca,
    0x3c, 0xea, 0x93, 0x0d, 0xc5, 0xcc, 0xc7, 0x76,
    0x7e, 0x2f, 0x77, 0xbd, 0x81, 0x53, 0xd1, 0xcd,
    0x20, 0x55, 0xe9, 0x35, 0xeb, 0x74, 0xe6, 0x16,
    0x38, 0x14, 0xad, 0xdf, 0x90, 0x11, 0x5c, 0x5d,
    0xef, 0xe6, 0xf8, 0x05, 0xb2, 0x04, 0xc4, 0x81,
    0x2c, 0xb8, 0xb8, 0x25, 0x2f, 0xd2, 0xaa, 0x43,
    0xd0, 0xce, 0xad, 0x51, 0x86, 0x80, 0x22, 0x9e,
    0x5b, 0x96, 0x01, 0x9e, 0x70, 0xe4, 0xce, 0x5a,
    0xc0, 0x60, 0x9d, 0x7c, 0x4c, 0x49, 0x96, 0x52,
    0xe3, 0xe5, 0x72, 0x40, 0xb5, 0x4e, 0x0b, 0xa6,
    0x05, 0x91, 0x16, 0xfe, 0x35, 0x44, 0x1a, 0x08,
    0x0e, 0x04, 0x65, 0x60, 0xb1, 0x49, 0xf7, 0x48,
    0xfc, 0x1c, 0xa9, 0x86, 0xeb, 0x01, 0x03, 0xdc,
    0x28, 0xd2, 0x84, 0x67, 0x18, 0xe0, 0x52, 0x10,
    0x35, 0xdd, 0x23, 0xa2, 0x13, 0x10, 0xfe, 0x71,
    0x32, 0x7b, 0x60, 0x08, 0x98, 0x3a, 0xc9, 0x85,
    0x7a, 0xe9, 0xb6, 0x00, 0x49, 0xd7, 0x85, 0x33,
    0x5d, 0x33, 0x1e, 0x58, 0x32, 0x91, 0xd5, 0xc7,
    0x9f, 0x00, 0x2b, 0xd0, 0x0a, 0xd8, 0x46, 0x90,
    0xe6, 0x90, 0x97, 0xb1, 0x8f, 0x95, 0x5c, 0x84,
    0xc0, 0x09, 0x54, 0xa4, 0xd6, 0x6b, 0xb9, 0xae,
    0x93, 0x54, 0x42, 0x2a, 0xed, 0xb0, 0xd4, 0x64,
    0x4f, 0x04, 0x07, 0x42, 0x69, 0xd2, 0xc4, 0x9f,
    0xc7, 0x06, 0x47, 0x2d, 0x68, 0xd8, 0x3d, 0xf4,
    0xa4, 0x89, 0xa4, 0x6d, 0x4a, 0x69, 0x49, 0x51,
    0xf8, 0x74, 0x4f, 0x78, 0xb7, 0x1f, 0x97, 0xa4,
    0xf9, 0x55, 0xea, 0xec, 0xa5, 0xcb, 0xd9, 0x63,
    0x92, 0x5d, 0x9a, 0xa8, 0xfb, 0x8f, 0xbb, 0xff,
    0x49, 0xf7, 0x3f, 0x85, 0x7f, 0x90, 0x3c, 0xdf,
    0x97, 0x1c, 0xa4, 0xab, 0x3d, 0xb9, 0x38, 0xc7,
    0x92, 0xf1, 0x29, 0x62, 0x19, 0x10, 0xc3, 0x03,
    0xcc, 0x87, 0xb5, 0xdd, 0xda, 0xc7, 0x0a, 0x1f,
    0xbe, 0x67, 0x63, 0xa6, 0x0b, 0x12, 0x40, 0x30,
    0xbb, 0x70, 0xb3, 0x0d, 0x94, 0x4b, 0x26, 0x44,
    0x41, 0xf0, 0x4a, 0x1e, 0x53, 0x66, 0xe4, 0x39,
    0x80, 0x77, 0x19, 0xba, 0x2c, 0x62, 0xcf, 0x62,
    0x9e, 0x43, 0xae, 0x9d, 0x36, 0xa5, 0x45, 0x3b,
    0xbb, 0xd2, 0xe8, 0x43, 0x30, 0xd0, 0x8a, 0x1b,
    0xc2, 0xb2, 0xf9, 0x92, 0xa5, 0xbe, 0x7d, 0x90,
    0x05, 0x38, 0x11, 0x03, 0xcd, 0x3f, 0xcc, 0xbc,
    0x93, 0x3e, 0xd5, 0xe1, 0xc4, 0x3b, 0xc1, 0x33,
    0x30, 0xa4, 0x94, 0x98, 0xdd, 0x21, 0xeb, 0xe9,
    0xe0, 0x62, 0x61, 0xb1, 0xb9, 0x27, 0x20, 0x50,
    0x81, 0xce, 0xcf, 0x69, 0xd8, 0x67, 0xe5, 0x00,
    0x93, 0x00, 0x07, 0xdc, 0x47, 0x07, 0x08, 0x7b,
    0xba, 0x26, 0x20, 0x85, 0xab, 0x0a, 0xc4, 0x5c,
    0x1c, 0x6e, 0x60, 0x8f, 0x83, 0x9c, 0x1e, 0x02,
    0xa6, 0x3f, 0x01, 0x3b, 0x42, 0xd5, 0x75, 0x19,
    0xbe, 0xbb, 0x88, 0xb3, 0x2b, 0x0b, 0xdd, 0xc0,
    0x94, 0x8f, 0x83, 0xdd, 0x00, 0x44, 0x3d, 0x46,
    0x9d, 0xf3, 0xbd, 0x85, 0x0f, 0x81, 0xa5, 0xe5,
    0x6c, 0x8f, 0x0c, 0x2f, 0xbb, 0x4e, 0x9e, 0x25,
    0x25, 0x3e, 0x97, 0x0b, 0x60, 0x60, 0x87, 0xd7,
    0xaa, 0xf9, 0x11, 0x57, 0x01, 0xcb, 0x5c, 0x2e,
    0x0f, 0xb2, 0xef, 0xa9, 0xaf, 0x47, 0x61, 0xeb,
    0x41, 0x3b, 0xdc, 0xc5, 0x09, 0x14, 0xb7, 0x40,
    0x71, 0xa4, 0x12, 0x12, 0x03, 0xf9, 0xe1, 0x40,
    0xb8, 0x05, 0x18, 0x17, 0x79, 0xba, 0x26, 0x84,
    0xe5, 0x94, 0xd1, 0x65, 0x90, 0x2a, 0xe8, 0xdd,
    0x29, 0x49, 0xbd, 0x54, 0xba, 0x56, 0x21, 0x98,
    0x3c, 0x8d, 0x9d, 0xa4, 0xc1, 0xa6, 0x43, 0x22,
    0xf0, 0x1c, 0x86, 0x4e, 0x87, 0x92, 0x46, 0x10,
    0x70, 0x67, 0x5f, 0x2d, 0x6c, 0xc7, 0x0e, 0xd5,
    0xf9, 0xe5, 0x85, 0xbc, 0x3e, 0xff, 0x15, 0x0d,
    0x75, 0x0c, 0x12, 0x2e, 0x3e, 0xdc, 0x5e, 0xfc,
    0x24, 0xdf, 0xdd, 0xad, 0x7e, 0xc6, 0xd0, 0x3c,
    0xe6, 0xdf, 0xd1, 0xe8, 0xfa, 0xe2, 0xd3, 0xe8,
    0x6c, 0xa4, 0x4c, 0x35, 0x89, 0x47, 0x47, 0xa3,
    0xbb, 0xd5, 0xc5, 0xea, 0xea, 0x97, 0x95, 0xfc,
    0x7c, 0x75, 0x73, 0x79, 0xfb, 0x19, 0x51, 0x3a,
    0x6c, 0xf0, 0x7e, 0x75, 0x77, 0x75, 0xfe, 0x41,
    0xfe, 0x70, 0xfe, 0xe9, 0x12, 0x17, 0x61, 0xbe,
    0xfb, 0x87, 0xf3, 0x87, 0x7b, 0x79, 0xff, 0xe9,
    0xfa, 0xfe, 0x67, 0x98, 0xb9, 0x5f, 0xe1, 0xcc,
    0x1c, 0x87, 0x57, 0x1f, 0x3f, 0xae, 0xee, 0x24,
    0xfe, 0xcb, 0x1f, 0x6e, 0x1f, 0x7e, 0x94, 0xab,
    0xcb, 0xf7, 0x30, 0x19, 0x7d, 0x45, 0xd4, 0xdc,
    0x02, 0x8e, 0xa7, 0x62, 0x96, 0x5a, 0x68, 0x61,
    0x81, 0x8e, 0xef, 0x3a, 0x66, 0x24, 0x09, 0xce,
    0x39, 0x3a, 0x1b, 0x03, 0x43, 0xaf, 0x62, 0x47,
    0x8a, 0x0f, 0x57, 0xf7, 0xf1, 0x25, 0x6c, 0x0b,
    0xd6, 0x87, 0xc7, 0xc9, 0xe5, 0x8f, 0x2c, 0x18,
    0x1c, 0x1e, 0x67, 0xdf, 0x7f, 0xbc, 0xba, 0x1d,
    0x8f, 0xce, 0xfe, 0x3d, 0x3e, 0x9a, 0x8e, 0xff,
    0x03, 0x9a, 0xe0, 0x3e, 0x02, 0x45, 0x7a, 0xf0,
    0xa9, 0xae, 0x78, 0xc3, 0xfe, 0x53, 0xb4, 0x37,
    0x69, 0x01, 0x7d, 0x47, 0x30, 0xd9, 0x23, 0xb0,
    0x65, 0x20, 0xce, 0xc6, 0x7e, 0x16, 0x4b, 0x67,
    0xec, 0xa8, 0x9d, 0xfa, 0xa1, 0xbc, 0x7c, 0xc6,
    0x91, 0xa5, 0x1f, 0xc1, 0x40, 0x84, 0x7c, 0x78,
    0xa4, 0x7e, 0xed, 0x4c, 0x8d, 0x44, 0x58, 0x6e,
    0x42, 0x47, 0x4a, 0xcc, 0x6c, 0x3c, 0x5d, 0x64,
    0xa4, 0x83, 0x5d, 0x33, 0x5f, 0x46, 0x73, 0x02,
    0x7a, 0xf8, 0x18, 0xcf, 0x0d, 0xf5, 0xa8, 0x9a,
    0x5c, 0xcd, 0xc6, 0x51, 0xfc, 0x08, 0xda, 0x46,
    0x61, 0xe0, 0x4b, 0x1a, 0x6d, 0xb0, 0x86, 0xe2,
    0x0b, 0x42, 0x78, 0x77, 0xeb, 0x02, 0x12, 0x8e,
    0x7e, 0xc4, 0x28, 0x9a, 0x01, 0x0a, 0xa9, 0xa8,
    0x32, 0x5b, 0x27, 0x3a, 0x57, 0xd9, 0x09, 0x27,
    0xd8, 0x90, 0x06, 0x43, 0x91, 0x9f, 0x5c, 0xf2,
    0x24, 0x99, 0xd7, 0x9a, 0xb1, 0x27, 0xed, 0x01,
    0x07, 0x41, 0x8e, 0xd0, 0x46, 0x14, 0x65, 0x23,
    0x12, 0x41, 0xb8, 0x46, 0x90, 0x20, 0x3e, 0x25,
    0x72, 0xcf, 0x88, 0xf0, 0x0c, 0x64, 0x17, 0x7f,
    0x6f, 0x44, 0xdd, 0x16, 0x62, 0xd7, 0xe6, 0x8d,
    0x46, 0x14, 0x05, 0x66, 0x69, 0x7b, 0xb5, 0x22,
    0x01, 0xe1, 0x45, 0xaa, 0x4e, 0x18, 0x6d, 0x30,
    0x87, 0x9b, 0x16, 0xdb, 0x84, 0xd7, 0x80, 0x1a,
    0x4a, 0x9b, 0x2d, 0x1c, 0xe1, 0x55, 0x35, 0x27,
    0x5c, 0x76, 0x75, 0xa4, 0x6d, 0x9e, 0x11, 0x05,
    0x9b, 0x7a, 0x5b, 0x2b, 0xda, 0x1a, 0xb0, 0x75,
    0xb5, 0x8c, 0x2e, 0xaa, 0xb6, 0x61, 0xfc, 0x31,
    0xe0, 0x80, 0x00, 0xcc, 0x6e, 0x2c, 0xd6, 0xb5,
    0x82, 0x78, 0x04, 0x15, 0xe5, 0x09, 0x03, 0x2c,
    0x22, 0x2c, 0xca, 0xe1, 0x46, 0x1e, 0x95, 0x2a,
    0x04, 0xf9, 0x38, 0xeb, 0x27, 0xee, 0x28, 0x43,
    0x05, 0x41, 0xe9, 0x2a, 0xda, 0xc2, 0xeb, 0xfc,
    0x44, 0x5c, 0x20, 0x5a, 0x87, 0xdd, 0x64, 0x10,
    0x63, 0x5e, 0x61, 0x3b, 0x29, 0x3a, 0x33, 0xde,
    0xc2, 0xc5, 0xed, 0xcd, 0xbb, 0xab, 0xf7, 0x12,
    0x3d, 0xf3, 0x6e, 0xf5, 0x6e, 0x75, 0xb7, 0xba,
    0xb9, 0x58, 0xc9, 0xeb, 0x5f, 0xc4, 0xb7, 0xba,
    0x81, 0x94, 0xb6, 0xd9, 0x36, 0xb0, 0xa0, 0x30,
    0x39, 0x3e, 0xe5, 0x54, 0x68, 0x7d, 0xf7, 0x37,
    0x2e, 0x28, 0xcf, 0x73, 0x6a, 0x7c, 0x0a, 0x5b,
    0x58, 0x66, 0x54, 0x4b, 0x5e, 0x24, 0x05, 0x1d,
    0x0b, 0x82, 0x15, 0x64, 0xfc, 0x35, 0x00, 0xa1,
    0xe7, 0x1d, 0xa3, 0x20, 0x41, 0x31, 0x47, 0x3c,
    0x6f, 0xe1, 0x62, 0x05, 0xc7, 0x0e, 0x23, 0x2a,
    0xb0, 0x72, 0xd8, 0x05, 0x37, 0x18, 0x2f, 0xe8,
    0x8e, 0xb0, 0xff, 0x6b, 0xf4, 0x06, 0x84, 0x8a,
    0x66, 0x0b, 0xf7, 0x02, 0xf7, 0x9b, 0x74, 0x4b,
    0x31, 0x40, 0x62, 0xe0, 0xd3, 0x11, 0x1b, 0x24,
    0xc5, 0xb8, 0x43, 0xc5, 0x29, 0x0f, 0x12, 0x58,
    0x24, 0x28, 0x0d, 0xab, 0x91, 0xb2, 0xb8, 0x7d,
    0x62, 0xd9, 0x11, 0xfc, 0x5f, 0x70, 0xdf, 0x5c,
    0x54, 0x49, 0x6d, 0x60, 0x8a, 0xb2, 0x0a, 0x77,
    0x00, 0xec, 0x0c, 0xdd, 0x86, 0x69, 0xc8, 0xc6,
    0xdf, 0x71, 0x53, 0xcb, 0x02, 0x20, 0x5d, 0x64,
    0xea, 0x45, 0xe4, 0x49, 0x8d, 0xc1, 0x11, 0x36,
    0x59, 0xf4, 0xfa, 0x5c, 0xdc, 0x85, 0xfd, 0xf1,
    0x57, 0xac, 0x3e, 0xb0, 0x7b, 0xf8, 0xcf, 0xce,
    0x1c, 0xfb, 0x37, 0x14, 0x1d, 0x4f, 0xb9, 0xda,
    0xb9, 0x42, 0xd3, 0x20, 0x73, 0x81, 0x79, 0x03,
    0x25, 0x6d, 0x60, 0xe6, 0xe8, 0xc4, 0x57, 0x0c,
    0xd8, 0x85, 0xaf, 0xf6, 0x86, 0xf5, 0x1a, 0xf5,
    0xd7, 0x2d, 0x99, 0x6d, 0xfb, 0xfa, 0x8e, 0x37,
    0xc3, 0x6b, 0xee, 0x99, 0x5b, 0xaa, 0xee, 0xb3,
    0x01, 0x37, 0x45, 0xfc, 0x20, 0xd0, 0xa1, 0x46,
    0x92, 0x9d, 0x82, 0xe3, 0x72, 0x8d, 0x6d, 0x27,
    0x77, 0x25, 0x40, 0xd3, 0x4e, 0x27, 0x02, 0xdb,
    0x8f, 0xdc, 0x1d, 0xb0, 0xd3, 0xae, 0x59, 0xe9,
    0xda, 0x93, 0xdc, 0x19, 0xdc, 0x9b, 0xef, 0x0a,
    0x6e, 0xb7, 0x01, 0xac, 0x0e, 0x2c, 0x11, 0x5c,
    0xa3, 0xe0, 0x18, 0x14, 0x2c, 0x8c, 0x6d, 0x42,
    0x9b, 0x41, 0x30, 0x9c, 0x07, 0xe3, 0x5d, 0x49,
    0x85, 0xf1, 0xb8, 0xe3, 0x9b, 0x06, 0x0a, 0xeb,
    0x95, 0x4c, 0x01, 0x0d, 0x56, 0x6d, 0xd7, 0x70,
    0x2f, 0x02, 0xc3, 0x6b, 0x45, 0x4e, 0x84, 0xbd,
    0xb6, 0xeb, 0xe4, 0x45, 0x24, 0x3b, 0x52, 0x01,
    0x5c, 0xc0, 0xc7, 0xcf, 0xd7, 0x36, 0x8c, 0x98,
    0xce, 0xca, 0x98, 0x32, 0x3e, 0x44, 0x89, 0xb6,
    0x56, 0x07, 0x74, 0xe2, 0x5e, 0x29, 0xa1, 0xd7,
    0xe2, 0xb5, 0x6c, 0x31, 0xf2, 0x88, 0xd6, 0x28,
    0xdc, 0x0e, 0x56, 0xab, 0xaa, 0xe7, 0xe7, 0x18,
    0xd6, 0x51, 0x1c, 0xc8, 0x59, 0xda, 0xab, 0xe3,
    0x16, 0xd6, 0xb5, 0x32, 0x26, 0x01, 0x3b, 0x01,
    0x42, 0x88, 0xd5, 0xce, 0x40, 0x41, 0x31, 0xd7,
    0xda, 0x18, 0x88, 0x41, 0x06, 0x0a, 0xf0, 0xac,
    0xcd, 0xd1, 0x87, 0x81, 0x1b, 0x8b, 0x13, 0xd1,
    0xa5, 0x62, 0x32, 0x34, 0xf5, 0x45, 0xe1, 0xa5,
    0x63, 0x99, 0xf1, 0x36, 0xc3, 0x36, 0xa9, 0x33,
    0xf2, 0x50, 0x4b, 0x8d, 0x7a, 0xc0, 0x8b, 0xa6,
    0x7a, 0x4d, 0xc0, 0x53, 0xbd, 0xe6, 0xe4, 0x01,
    0x3a, 0xbb, 0x6d, 0x9b, 0xb7, 0x2d, 0x15, 0x7b,
    0x3e, 0xa8, 0x89, 0x37, 0x66, 0x81, 0xfd, 0x4e,
    0x75, 0x1b, 0x80, 0xad, 0x90, 0xbe, 0xc0, 0x8d,
    0x48, 0x29, 0x55, 0x82, 0x5e, 0x86, 0x8d, 0x96,
    0x7b, 0x47, 0xb0, 0x77, 0x12, 0xf1, 0xac, 0xf3,
    0x1c, 0xd0, 0x4a, 0xaa, 0x28, 0x83, 0xf8, 0x1e,
    0x34, 0x57, 0xfc, 0x9e, 0xd3, 0x9d, 0xe6, 0x0f,
    0x38, 0xb0, 0x17, 0x73, 0x0f, 0x21, 0x82, 0x15,
    0x4e, 0x1b, 0x40, 0x0a, 0xbd, 0x6b, 0x77, 0x76,
    0xcc, 0xfa, 0x0c, 0x78, 0xf2, 0xbd, 0xed, 0x1c,
    0xd3, 0x17, 0x22, 0x10, 0x46, 0x41, 0x85, 0x82,
    0x9c, 0xfb, 0x58, 0x84, 0x9f, 0xcf, 0xee, 0xbb,
    0x30, 0xd3, 0x94, 0x25, 0xa4, 0x2f, 0x3a, 0x1e,
    0x1f, 0x0d, 0xbf, 0x0c, 0x3c, 0x84, 0xc6, 0x88,
    0xd1, 0x0c, 0x08, 0xa9, 0xb5, 0xce, 0x5d, 0x82,
    0x07, 0x52, 0x08, 0x72, 0x42, 0x2e, 0x30, 0x8a,
    0x3f, 0x23, 0x7d, 0xbe, 0x7c, 0xb0, 0x89, 0x0b,
    0x42, 0x79, 0xda, 0xe6, 0xe8, 0x38, 0xcf, 0x49,
    0x93, 0x6e, 0x33, 0x48, 0x29, 0x15, 0x84, 0x39,
    0x2c, 0xe3, 0xea, 0x13, 0x6e, 0x69, 0xd1, 0xd7,
    0x3b, 0xc0, 0x26, 0x6d, 0xf1, 0xd4, 0x65, 0x4f,
    0xfe, 0xae, 0x15, 0x8c, 0x1b, 0x3f, 0x11, 0xe3,
    0x27, 0x3d, 0x74, 0x1e, 0x40, 0xeb, 0x06, 0xb2,
    0x05, 0xda, 0x24, 0x00, 0x41, 0x23, 0x52, 0x23,
    0x08, 0x53, 0x60, 0x1f, 0x0a, 0xd1, 0x10, 0xfa,
    0x8c, 0x00, 0x18, 0x04, 0xf9, 0xc4, 0xb4, 0x15,
    0x86, 0x1b, 0xe4, 0xc7, 0xc6, 0x84, 0x9f, 0x65,
    0x87, 0xe3, 0x6a, 0xcb, 0x8d, 0xa2, 0xdf, 0xf6,
    0x79, 0x7c, 0xef, 0x98, 0x23, 0x74, 0x59, 0x40,
    0x46, 0x49, 0xbe, 0xc0, 0x96, 0x92, 0xc7, 0xdc,
    0xc6, 0xea, 0xf0, 0xfb, 0x1b, 0xa2, 0x94, 0x5c,
    0x0c, 0xd6, 0x00, 0x13, 0xa5, 0xef, 0x93, 0x2e,
    0x29, 0x74, 0x5f, 0x2d, 0x33, 0xea, 0xc1, 0x1a,
    0xec, 0x08, 0x62, 0xb0, 0x65, 0x13, 0x03, 0x05,
    0xd1, 0x79, 0xb1, 0x69, 0x66, 0x1b, 0xd6, 0x54,
    0x14, 0xa1, 0xaa, 0x29, 0x80, 0xf3, 0x27, 0x97,
    0x03, 0x58, 0x16, 0x2f, 0x98, 0x03, 0x09, 0xb6,
    0xff, 0xbb, 0xe4, 0xc1, 0x8e, 0x81, 0x5f, 0x54,
    0x00, 0xeb, 0xec, 0xb5, 0xc8, 0x11, 0xec, 0x00,
    0xbc, 0x9d, 0x44, 0xcb, 0xd9, 0x8c, 0xe0, 0x53,
    0xf7, 0x32, 0x27, 0xfc, 0xc4, 0x2f, 0xf3, 0x19,
    0x85, 0x6b, 0x78, 0x99, 0xcf, 0x17, 0xf0, 0x3c,
    0xf9, 0xba, 0x57, 0x2f, 0x90, 0xaf, 0x9f, 0x91,
    0xb0, 0xdb, 0x9b, 0xab, 0x87, 0xdb, 0x3b, 0xe2,
    0xb8, 0xfd, 0x65, 0x75, 0xf7, 0xee, 0x03, 0x21,
    0x60, 0x70, 0xa6, 0xf3, 0xcf, 0xf2, 0xee, 0xfc,
    0x06, 0x61, 0x2c, 0x02, 0xdf, 0xd5, 0xcd, 0xfd,
    0x2d, 0x00, 0xdc, 0x8f, 0xab, 0x8b, 0xab, 0x77,
    0x57, 0x17, 0x07, 0x85, 0x3a, 0x6c, 0xf7, 0x68,
    0x24, 0x9e, 0x1a, 0xd8, 0x32, 0xbd, 0x5e, 0x43,
    0x1a, 0x49, 0x9e, 0xe4, 0x86, 0x73, 0x08, 0xfe,
    0x45, 0x5f, 0x09, 0xe5, 0xa6, 0x60, 0x16, 0x40,
    0x35, 0x7a, 0x7f, 0xf3, 0x49, 0xbc, 0xff, 0xf8,
    0xe1, 0xcb, 0x64, 0x44, 0x4d, 0x98, 0x0a, 0xe2,
    0x93, 0xe2, 0x8f, 0xcd, 0xee, 0x83, 0x70, 0xaf,
    0x78, 0xa7, 0x26, 0x49, 0xbf, 0x0b, 0xd4, 0xd5,
    0xa6, 0xa7, 0xc1, 0x27, 0xdb, 0x1e, 0x4b, 0x12,
    0xb4, 0x11, 0xb9, 0xc6, 0x67, 0x86, 0x63, 0x82,
    0xb0, 0x04, 0x8d, 0x7c, 0x9d, 0x73, 0xec, 0xbf,
    0xd3, 0x09, 0x84, 0xe2, 0xf4, 0x44, 0xa5, 0x10,
    0xf5, 0xb3, 0x71, 0xcc, 0x9a, 0x10, 0x15, 0xe5,
    0x10, 0xc2, 0xa4, 0x6b, 0x2f, 0x21, 0x3b, 0x7d,
    0x00, 0xa1, 0xce, 0xe2, 0x1f, 0x6d, 0xbc, 0x63,
    0xe9, 0x1e, 0x64, 0xb0, 0x3e, 0x42, 0x38, 0xfb,
    0x15, 0xc1, 0x80, 0xff, 0xba, 0x8f, 0x02, 0xc7,
    0x08, 0x63, 0x2d, 0x68, 0xef, 0x89, 0x86, 0xf2,
    0x16, 0x82, 0xee, 0xfe, 0x22, 0x61, 0x93, 0x1f,
    0xf9, 0xe7, 0xbe, 0xa3, 0x2d, 0xad, 0xae, 0x83,
    0xd6, 0x36, 0x17, 0xf0, 0x27, 0xa8, 0x1a, 0x38,
    0x44, 0x70, 0x50, 0x31, 0x04, 0xdd, 0xdd, 0x59,
    0x11, 0x1a, 0xba, 0x46, 0x77, 0xb7, 0x5b, 0xdb,
    0xe2, 0x68, 0xd3, 0x14, 0x12, 0x4c, 0xb7, 0x30,
    0xb8, 0x1a, 0x2c, 0x16, 0x7e, 0x2b, 0x39, 0x8e,
    0xa9, 0x9f, 0x85, 0xa1, 0x41, 0x3e, 0xb6, 0xf9,
    0x53, 0xaf, 0x93, 0x60, 0x38, 0x7f, 0xa9, 0x41,
    0xab, 0xfc, 0x38, 0x1a, 0xf0, 0xf4, 0xba, 0xa1,
    0xbe, 0x50, 0xef, 0x1a, 0x9a, 0xb6, 0x02, 0xe5,
    0xb6, 0x5a, 0x28, 0xf2, 0xb1, 0x5d, 0xaf, 0x15,
    0x04, 0x5a, 0xee, 0xf6, 0x42, 0x4e, 0x85, 0xe8,
    0x20, 0x6d, 0x2e, 0x32, 0xdd, 0xe1, 0x10, 0xaa,
    0x19, 0x1f, 0x99, 0x6d, 0xe3, 0xfb, 0x0d, 0x4d,
    0x44, 0x87, 0xda, 0x45, 0x81, 0x92, 0xf7, 0x1b,
    0xaa, 0x34, 0x61, 0x95, 0x31, 0xee, 0xb7, 0x67,
    0xf6, 0x18, 0x07, 0xf4, 0x08, 0xaa, 0x08, 0xa1,
    0x13, 0xb4, 0x3d, 0x8e, 0x27, 0x5c, 0x17, 0x19,
    0x6f, 0x56, 0xa6, 0xdd, 0x75, 0x7f, 0xe6, 0x37,
    0xae, 0xdf, 0x67, 0xbe, 0xe5, 0x32, 0xe8, 0xc7,
    0xf0, 0x57, 0x09, 0x8d, 0x72, 0xe7, 0x83, 0xa0,
    0xd3, 0xbf, 0xd4, 0x03, 0xbe, 0x87, 0x0f, 0x94,
    0x66, 0xf8, 0xa6, 0xa3, 0xa0, 0x4d, 0xb3, 0x7f,
    0x06, 0x6c, 0xd0, 0xf0, 0xfe, 0xa7, 0xfb, 0x3d,
    0x8c, 0xc3, 0x06, 0xcd, 0x4f, 0xa1, 0x7f, 0x44,
    0x93, 0xb0, 0x11, 0xe1, 0x79, 0x20, 0x8f, 0xd9,
    0x7e, 0xc2, 0xe1, 0xc6, 0x4e, 0x28, 0x83, 0x22,
    0x32, 0x01, 0x78, 0xfe, 0x10, 0xdc, 0xf6, 0x22,
    0x00, 0xd6, 0x99, 0x5d, 0x45, 0x04, 0x11, 0xea,
    0x5f, 0x70, 0x3d, 0xf1, 0x7c, 0x3c, 0x8b, 0x26,
    0x12, 0xea, 0xe0, 0xf1, 0x74, 0x76, 0x0c, 0xe0,
    0xae, 0x3e, 0xc9, 0x93, 0x62, 0xf4, 0xf5, 0x7f,
    0xdc, 0x51, 0x17, 0x79,
};

// Identify size = 3284 (9124 uncompressed)
const uint32_t command_identify_size PROGMEM
    = ARRAY_SIZE(command_identify_data);
